#!/usr/bin/env sh
set -e
set -x

echo "OpenLDAP installer stub"

DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y --force-yes slapd time ldap-utils

BASE_PATH="$( cd `dirname $0`/../test/fixtures/openldap && pwd )"

sudo /etc/init.d/slapd stop

# setup base configuration, schemas
sudo slapadd -F /etc/ldap/slapd.d -b "cn=config" -l $BASE_PATH/slapd.conf.ldif
# load memberof and ref-int overlays and configure them
sudo slapadd -F /etc/ldap/slapd.d -b "cn=config" -l $BASE_PATH/memberof.ldif

# Add base domain.
sudo slapadd -F /etc/ldap/slapd.d <<EOM
dn: dc=github,dc=org
objectClass: top
objectClass: domain
dc: github
EOM

sudo chown -R openldap.openldap /etc/ldap/slapd.d
sudo chown -R openldap.openldap /var/lib/ldap

sudo /etc/init.d/slapd start

# Import seed data.
# NOTE: use ldapadd in order for memberOf and refint to apply, instead of:
# /vagrant/services/ldap/openldap/seed.rb | sudo slapadd -F /etc/ldap/slapd.d
cat $BASE_PATH/seed.ldif |
  /usr/bin/time sudo ldapadd -x -D "cn=admin,dc=github,dc=org" -w passworD1 \
               -h localhost -p 389
